name: Basic checkings (all branches)
permissions:
  contents: read

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    uses: ./.github/workflows/lint.job.yml

  typecheck:
    uses: ./.github/workflows/typecheck.job.yml

  tests:
    uses: ./.github/workflows/unit-tests.job.yml
