on: workflow_call
permissions:
  contents: read

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Install dependencies with Yarn
        run: yarn install --frozen-lockfile

      - name: Build Project
        run: yarn build
        continue-on-error: false

      - name: Upload dist artifact
        uses: actions/upload-artifact@v7
        with:
          path: dist
          name: dist-${{ github.sha }}
          if-no-files-found: error
