name: Release and Publish
permissions:
  contents: write
  id-token: write # required for provenance support
  packages: write

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  lint:
    uses: ./.github/workflows/lint.job.yml

  typecheck:
    uses: ./.github/workflows/typecheck.job.yml

  tests:
    uses: ./.github/workflows/unit-tests.job.yml

  build:
    needs:
      - lint
      - typecheck
      - tests
    uses: ./.github/workflows/build.job.yml

  publish:
    needs:
      - build
    uses: ./.github/workflows/publish.job.yml
    secrets:
      NPM_REGISTRY_PAT: ${{ secrets.NPM_REGISTRY_PAT }}
